version: 1

sources:
  - name: gold
    description: "Tables for a specific question or ML model"
    database: nfl_data
    schema: gold
    tables:
      - name: yards_by_formation
        description: "Average total yards (rushing + receiving on a play) by offensive formation and receiver alignment"

  - name: silver
    description: "Aggregated NFL data from Bronze tables"
    database: nfl_data
    schema: silver
    tables:
      - name: agg_play_summary
        description: "Presnap offensive formation and alignment, play type, outcome event"


  - name: bronze
    description: "Raw NFL data from CSV files"
    database: nfl_data
    schema: bronze
    tables:
      - name: games
        description: "Games data"
        path: "../../data/raw/games.csv"
      - name: player_play
        description: "Player play data"
        path: "../../data/raw/player_play.csv"  # Path to the CSV file
      - name: players
        description: "Players data"
        path: "../../data/raw/players.csv"
      - name: plays
        description: "Plays data"
        path: "../../data/raw/plays.csv"
      - name: tracking_week_1
        description: "Tracking data for week 1"
        path: "../../data/raw/tracking_week_1.csv"
      - name: tracking_week_2
        description: "Tracking data for week 2"
        path: "../../data/raw/tracking_week_2.csv"
      - name: tracking_week_3
        description: "Tracking data for week 3"
        path: "../../data/raw/tracking_week_3.csv"
      - name: tracking_week_4
        description: "Tracking data for week 4"
        path: "../../data/raw/tracking_week_4.csv"
      - name: tracking_week_5
        description: "Tracking data for week 5"
        path: "../../data/raw/tracking_week_5.csv"
      - name: tracking_week_6
        description: "Tracking data for week 6"
        path: "../../data/raw/tracking_week_6.csv"
      - name: tracking_week_7
        description: "Tracking data for week 7"
        path: "../../data/raw/tracking_week_7.csv"
      - name: tracking_week_8
        description: "Tracking data for week 8"
        path: "../../data/raw/tracking_week_8.csv"
      - name: tracking_week_9
        description: "Tracking data for week 9"
        path: "../../data/raw/tracking_week_9.csv"
